/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "beanstorm_schema.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PControlPoint, PControlPoint, AUTO)


PB_BIND(PBrewProfile, PBrewProfile, AUTO)


PB_BIND(PPID, PPID, AUTO)




